on: pull_request

jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install package
        run: just setup-pnpm
      - name: Lint
        run: just lint-md
  lint_python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: ts-graphviz/setup-graphviz@v2
      - name: Install dependencies
        run: |
          just setup-py
      - name: Generate files using just
        run: |
          just lint-py
      - name: commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if git diff-index --quiet HEAD; then
            exit 0
          fi
          git add .
          git commit -m "style: lint"
          git push
